app:
    resource: '@AppBundle/Controller/'
    type: annotation

post_list:
    path:     post/list/{page}
    defaults:  { _controller: AppBundle:Post:list, page: 1 }
    requirements:
        page: '\d+'